version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - '9000:9000'

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: url_shortener
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: root
            MYSQL_PASSWORD: password # Add password for laravel_user

        ports:
            - '3306:3306'

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
        depends_on:
            - app
